name: Python application

on:
  push:
    branches: [ "DEV" ]
  pull_request:
    branches: [ "DEV" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Render Deployment
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_DEV_API_KEY }}